apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init
  namespace: dummycorp-store
spec:
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-mongodb
          image: mongo:6.0
          command:
            - "bash"
            - "-c"
            - |
              for i in {1..30}; do
                if mongosh --host mongodb --port 27017 -u admin -p password --eval "db.runCommand({ ping: 1 })"; then
                  echo "MongoDB está listo!"
                  exit 0
                fi
                echo "Esperando a que MongoDB esté listo... (intento $i/30)"
                sleep 10
              done
              echo "Error: MongoDB no estuvo listo después de 5 minutos"
              exit 1
      containers:
        - name: mongodb-init
          image: mongo:6.0
          command:
            - "bash"
            - "-c"
            - |
              mongoimport --host mongodb --port 27017 --username admin --password password --db mydb --collection products --drop --jsonArray < /fixtures/products.json
          volumeMounts:
            - name: fixtures
              mountPath: /fixtures
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
      volumes:
        - name: fixtures
          configMap:
            name: mongodb-fixtures
  backoffLimit: 4