# .github/workflows/build-push-ecr.yaml
name: Build and Push to ECR

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  AWS_REGION: eu-west-1

jobs:
  build-and-push:
    name: Build and Push Images
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/dummycorp-store-frontend:latest
            ${{ steps.login-ecr.outputs.registry }}/dummycorp-store-frontend:${{ github.sha }}
          # Eliminamos las opciones de caché que están causando problemas
          # cache-from: type=gha
          # cache-to: type=gha,mode=max

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/dummycorp-store-backend:latest
            ${{ steps.login-ecr.outputs.registry }}/dummycorp-store-backend:${{ github.sha }}
          # Eliminamos las opciones de caché que están causando problemas
          # cache-from: type=gha
          # cache-to: type=gha,mode=max